"""add_activity_likes_comments

Revision ID: 0f83bd315a70
Revises: a8c1d2e3f4a5
Create Date: 2026-05-03 20:13:14.777064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f83bd315a70'
down_revision: Union[str, None] = 'a8c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_reference_id'), 'activities', ['reference_id'], unique=False)
    op.create_index(op.f('ix_activities_user_identifier'), 'activities', ['user_identifier'], unique=False)
    op.create_table('activity_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_comments_activity_id'), 'activity_comments', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_comments_user_identifier'), 'activity_comments', ['user_identifier'], unique=False)
    op.create_table('activity_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'user_identifier', name='uq_activity_user_like')
    )
    op.create_index(op.f('ix_activity_likes_activity_id'), 'activity_likes', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_likes_user_identifier'), 'activity_likes', ['user_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_likes_user_identifier'), table_name='activity_likes')
    op.drop_index(op.f('ix_activity_likes_activity_id'), table_name='activity_likes')
    op.drop_table('activity_likes')
    op.drop_index(op.f('ix_activity_comments_user_identifier'), table_name='activity_comments')
    op.drop_index(op.f('ix_activity_comments_activity_id'), table_name='activity_comments')
    op.drop_table('activity_comments')
    op.drop_index(op.f('ix_activities_user_identifier'), table_name='activities')
    op.drop_index(op.f('ix_activities_reference_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
