"""add species cols to sightings plus binders tables

Revision ID: 297b6d575435
Revises: f024f9f8c700
Create Date: 2026-05-03 14:38:55.978440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297b6d575435'
down_revision: Union[str, None] = 'f024f9f8c700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('cover_card_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binders_user_identifier'), 'binders', ['user_identifier'], unique=False)
    op.create_table('binder_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('binder_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('binder_id', 'card_id', name='uq_binder_card')
    )
    op.create_index(op.f('ix_binder_cards_binder_id'), 'binder_cards', ['binder_id'], unique=False)
    op.create_index(op.f('ix_binder_cards_card_id'), 'binder_cards', ['card_id'], unique=False)
    op.add_column('sightings', sa.Column('species_code', sa.String(length=6), nullable=True))
    op.add_column('sightings', sa.Column('species_common', sa.String(length=255), nullable=True))
    op.add_column('sightings', sa.Column('species_scientific', sa.String(length=255), nullable=True))
    op.add_column('sightings', sa.Column('family', sa.String(length=255), nullable=True))
    op.add_column('sightings', sa.Column('pose_variant', sa.String(length=20), nullable=True))
    op.add_column('sightings', sa.Column('id_confidence', sa.Float(), nullable=True))
    op.add_column('sightings', sa.Column('id_method', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_sightings_species_code'), 'sightings', ['species_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sightings_species_code'), table_name='sightings')
    op.drop_column('sightings', 'id_method')
    op.drop_column('sightings', 'id_confidence')
    op.drop_column('sightings', 'pose_variant')
    op.drop_column('sightings', 'family')
    op.drop_column('sightings', 'species_scientific')
    op.drop_column('sightings', 'species_common')
    op.drop_column('sightings', 'species_code')
    op.drop_index(op.f('ix_binder_cards_card_id'), table_name='binder_cards')
    op.drop_index(op.f('ix_binder_cards_binder_id'), table_name='binder_cards')
    op.drop_table('binder_cards')
    op.drop_index(op.f('ix_binders_user_identifier'), table_name='binders')
    op.drop_table('binders')
    # ### end Alembic commands ###
