"""initial schema

Revision ID: f024f9f8c700
Revises: 
Create Date: 2026-05-03 12:27:58.768189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f024f9f8c700'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_identifier', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('season', sa.String(length=100), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('card_targets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_sets_creator_identifier'), 'card_sets', ['creator_identifier'], unique=False)
    op.create_index(op.f('ix_card_sets_name'), 'card_sets', ['name'], unique=False)
    op.create_table('sightings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exif_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exif_lat', sa.Float(), nullable=True),
    sa.Column('exif_lon', sa.Float(), nullable=True),
    sa.Column('exif_camera_model', sa.String(length=255), nullable=True),
    sa.Column('location_display_name', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('manual_species_override', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sightings_status'), 'sightings', ['status'], unique=False)
    op.create_index(op.f('ix_sightings_user_identifier'), 'sightings', ['user_identifier'], unique=False)
    op.create_table('species_cache',
    sa.Column('species_code', sa.String(length=6), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('taxon_order', sa.Integer(), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('family_common', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('species_code')
    )
    op.create_index(op.f('ix_species_cache_common_name'), 'species_cache', ['common_name'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('offered_by', sa.String(length=255), nullable=False),
    sa.Column('offered_to', sa.String(length=255), nullable=False),
    sa.Column('offered_card_ids', sa.JSON(), nullable=False),
    sa.Column('requested_card_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_offered_by'), 'trades', ['offered_by'], unique=False)
    op.create_index(op.f('ix_trades_offered_to'), 'trades', ['offered_to'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sighting_id', sa.String(length=36), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('species_common', sa.String(length=255), nullable=False),
    sa.Column('species_scientific', sa.String(length=255), nullable=True),
    sa.Column('species_code', sa.String(length=6), nullable=False),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('pose_variant', sa.String(length=20), nullable=False),
    sa.Column('rarity_tier', sa.String(length=20), nullable=False),
    sa.Column('set_ids', sa.JSON(), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.Column('card_art_url', sa.String(length=512), nullable=True),
    sa.Column('id_method', sa.String(length=20), nullable=False),
    sa.Column('id_confidence', sa.Float(), nullable=True),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('tradeable', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_species_code'), 'cards', ['species_code'], unique=False)
    op.create_index(op.f('ix_cards_species_common'), 'cards', ['species_common'], unique=False)
    op.create_index(op.f('ix_cards_user_identifier'), 'cards', ['user_identifier'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sighting_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_cards_user_identifier'), table_name='cards')
    op.drop_index(op.f('ix_cards_species_common'), table_name='cards')
    op.drop_index(op.f('ix_cards_species_code'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_offered_to'), table_name='trades')
    op.drop_index(op.f('ix_trades_offered_by'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_species_cache_common_name'), table_name='species_cache')
    op.drop_table('species_cache')
    op.drop_index(op.f('ix_sightings_user_identifier'), table_name='sightings')
    op.drop_index(op.f('ix_sightings_status'), table_name='sightings')
    op.drop_table('sightings')
    op.drop_index(op.f('ix_card_sets_name'), table_name='card_sets')
    op.drop_index(op.f('ix_card_sets_creator_identifier'), table_name='card_sets')
    op.drop_table('card_sets')
    # ### end Alembic commands ###
